# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=87)),
                ('nickname', models.CharField(max_length=87)),
                ('birthdayy', models.DecimalField(decimal_places=0, max_digits=7)),
                ('constellation', models.CharField(max_length=87)),
                ('sexs', models.CharField(max_length=2)),
                ('stunumber', models.CharField(max_length=12)),
            ],
        ),
    ]
