# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graphh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=87)),
                ('discribe', models.CharField(max_length=87)),
                ('picture', models.CharField(max_length=87)),
                ('googleconnect', models.CharField(max_length=87)),
                ('suggest', models.CharField(max_length=878)),
                ('score', models.CharField(max_length=12)),
                ('telephone',models.DecimalField(max_digits=11,decimal_places=0)),
                ('place',models.CharField(max_length=87)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('score', models.DecimalField(max_digits=7,decimal_places=0)),
                ('pub_date',models.DateTimeField('date published')),
            ],
        ),
    ]
