# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=87)),
                ('hreflink', models.CharField(max_length=887)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=0, max_digits=7)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=87)),
                ('Telephone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Address', models.CharField(max_length=87)),
                ('googleconnect', models.CharField(max_length=887)),
            ],
        ),
    ]
